<template>
  <div>
    <!-- Hero Section -->
    <section class="relative overflow-hidden bg-gradient-to-br from-primary-50 via-white to-blue-50 py-20 lg:py-32">
      <div class="absolute inset-0 bg-grid-pattern opacity-5"></div>
      <div class="absolute -top-24 -right-24 w-96 h-96 bg-primary-300 rounded-full filter blur-3xl opacity-20"></div>
      <div class="absolute -bottom-24 -left-24 w-96 h-96 bg-blue-300 rounded-full filter blur-3xl opacity-20"></div>
      
      <UContainer>
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          <div class="lg:col-span-6 space-y-8 z-10">
            <div class="inline-flex items-center px-3 py-1 rounded-full bg-primary-100 text-primary-800 text-sm font-medium mb-2">
              <UIcon name="i-heroicons-sparkles" class="w-4 h-4 mr-2" />
              AI-Powered Learning Platform
            </div>
            
            <div class="space-y-6">
              <h1 class="text-5xl lg:text-6xl font-bold text-gray-900 leading-tight">
                Learn <span class="text-primary-600">Anything</span>, Anytime, <span class="relative">
                  Anywhere
                  <span class="absolute bottom-1 left-0 w-full h-3 bg-primary-200 -z-10"></span>
                </span>
              </h1>
              <p class="text-xl text-gray-600 leading-relaxed max-w-2xl">
                Get personalized courses, quizzes, and schedules generated by AI. 
                Learn at your own pace with content tailored to your goals and availability.
              </p>
            </div>
            
            <div class="flex flex-col sm:flex-row gap-4">
              <UButton to="/auth/register" size="xl" class="justify-center">
                Start Learning Free
                <UIcon name="i-heroicons-arrow-right" class="w-5 h-5 ml-2" />
              </UButton>
              <UButton to="#demo" variant="outline" size="xl" class="justify-center">
                Watch Demo
                <UIcon name="i-heroicons-play" class="w-5 h-5 ml-2" />
              </UButton>
            </div>
            
            <div class="flex flex-wrap items-center gap-6 pt-4">
              <div class="flex items-center space-x-2">
                <UIcon name="i-heroicons-check-circle" class="w-5 h-5 text-green-600" />
                <span class="text-gray-700">Free 14-day trial</span>
              </div>
              <div class="flex items-center space-x-2">
                <UIcon name="i-heroicons-check-circle" class="w-5 h-5 text-green-600" />
                <span class="text-gray-700">No credit card required</span>
              </div>
              <div class="flex items-center space-x-2">
                <UIcon name="i-heroicons-check-circle" class="w-5 h-5 text-green-600" />
                <span class="text-gray-700">Cancel anytime</span>
              </div>
            </div>
          </div>
          
          <div class="lg:col-span-6 relative z-10">
            <div class="relative">
              <!-- Decorative elements -->
              <div class="absolute -top-6 -left-6 w-12 h-12 bg-yellow-400 rounded-lg rotate-12"></div>
              <div class="absolute -bottom-6 -right-6 w-12 h-12 bg-primary-400 rounded-full"></div>
              
              <!-- Main course card -->
              <div class="bg-white rounded-2xl shadow-2xl p-6 transform hover:scale-105 transition-transform duration-300 relative z-20">
                <div class="space-y-4">
                  <div class="flex items-center justify-between">
                    <div class="flex items-center space-x-3">
                      <div class="w-10 h-10 bg-primary-100 rounded-lg flex items-center justify-center">
                        <UIcon name="i-heroicons-academic-cap" class="w-6 h-6 text-primary-600" />
                      </div>
                      <div>
                        <h3 class="font-semibold text-gray-900">JavaScript Fundamentals</h3>
                        <p class="text-sm text-gray-600">AI-generated course</p>
                      </div>
                    </div>
                    <UBadge color="green" variant="subtle">In Progress</UBadge>
                  </div>
                  
                  <div class="space-y-2">
                    <div class="flex justify-between text-sm">
                      <span class="text-gray-600">Progress</span>
                      <span class="font-medium">65%</span>
                    </div>
                    <div class="w-full bg-gray-200 rounded-full h-2">
                      <div class="bg-primary-600 h-2 rounded-full" style="width: 65%"></div>
                    </div>
                  </div>
                  
                  <div class="grid grid-cols-2 gap-2">
                    <div class="bg-gray-50 p-3 rounded-lg">
                      <div class="text-sm text-gray-500">Lessons</div>
                      <div class="font-semibold text-gray-900 flex items-center">
                        <UIcon name="i-heroicons-book-open" class="w-4 h-4 mr-1 text-primary-600" />
                        12 lessons
                      </div>
                    </div>
                    <div class="bg-gray-50 p-3 rounded-lg">
                      <div class="text-sm text-gray-500">Duration</div>
                      <div class="font-semibold text-gray-900 flex items-center">
                        <UIcon name="i-heroicons-clock" class="w-4 h-4 mr-1 text-primary-600" />
                        4 weeks
                      </div>
                    </div>
                  </div>
                  
                  <div class="border-t pt-4">
                    <div class="flex items-center justify-between">
                      <div class="flex -space-x-2">
                        <UAvatar src="/placeholder.svg?height=32&width=32" alt="User" size="sm" />
                        <UAvatar src="/placeholder.svg?height=32&width=32" alt="User" size="sm" />
                        <UAvatar src="/placeholder.svg?height=32&width=32" alt="User" size="sm" />
                        <div class="w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center text-xs text-gray-600">+24</div>
                      </div>
                      <UButton size="sm">Continue Learning</UButton>
                    </div>
                  </div>
                </div>
              </div>
              
              <!-- Secondary cards -->
              <div class="absolute top-1/4 -right-16 w-64 bg-white rounded-xl shadow-lg p-4 transform -rotate-6 z-10">
                <div class="flex items-center space-x-3">
                  <div class="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center">
                    <UIcon name="i-heroicons-puzzle-piece" class="w-4 h-4 text-blue-600" />
                  </div>
                  <div>
                    <h4 class="font-medium text-gray-900">Interactive Quiz</h4>
                    <div class="text-xs text-gray-600">10 questions</div>
                  </div>
                </div>
              </div>
              
              <div class="absolute bottom-1/4 -left-12 w-56 bg-white rounded-xl shadow-lg p-4 transform rotate-6 z-10">
                <div class="flex items-center space-x-3">
                  <div class="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center">
                    <UIcon name="i-heroicons-calendar" class="w-4 h-4 text-green-600" />
                  </div>
                  <div>
                    <h4 class="font-medium text-gray-900">Study Schedule</h4>
                    <div class="text-xs text-gray-600">Personalized for you</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Trusted by section -->
        <div class="mt-20 text-center">
          <p class="text-gray-600 mb-8">Trusted by learners from leading companies</p>
          <div class="flex flex-wrap justify-center items-center gap-8 opacity-70">
            <div class="h-8 w-auto">
              <svg class="h-full w-auto text-gray-400" viewBox="0 0 124 24" fill="currentColor">
                <path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm0 4.5c1.103 0 2 .897 2 2s-.897 2-2 2-2-.897-2-2 .897-2 2-2zm3 13.5h-6v-1.5c0-.551.449-1 1-1h4c.551 0 1 .449 1 1V18zm3-4.5h-12v-1.5c0-.551.449-1 1-1h10c.551 0 1 .449 1 1V13.5z"/>
                <path d="M42 6h-6v12h2v-4h4c2.206 0 4-1.794 4-4s-1.794-4-4-4zm0 6h-4V8h4c1.103 0 2 .897 2 2s-.897 2-2 2zM55 10h-4V8h6V6h-6c-1.103 0-2 .897-2 2v8c0 1.103.897 2 2 2h6v-2h-6v-4h4v-2zM63 6h2v12h-2zM72 6h-4c-1.103 0-2 .897-2 2v8c0 1.103.897 2 2 2h4c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2zm0 10h-4V8h4v8zM84 10h-4V8h6V6h-6c-1.103 0-2 .897-2 2v8c0 1.103.897 2 2 2h6v-2h-6v-4h4v-2zM96 6h2v12h-2zM106 6h-4c-1.103 0-2 .897-2 2v8c0 1.103.897 2 2 2h4c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2zm0 10h-4V8h4v8z"/>
              </svg>
            </div>
            <div class="h-5 w-auto">
              <svg class="h-full w-auto text-gray-400" viewBox="0 0 124 24" fill="currentColor">
                <path d="M24 12c0 6.627-5.373 12-12 12S0 18.627 0 12 5.373 0 12 0s12 5.373 12 12zm-4 0c0-4.418-3.582-8-8-8s-8 3.582-8 8 3.582 8 8 8 8-3.582 8-8zM44 6h-6v12h2v-4h4c2.206 0 4-1.794 4-4s-1.794-4-4-4zm0 6h-4V8h4c1.103 0 2 .897 2 2s-.897 2-2 2zM57 18h2V6h-2zM66 6c-3.308 0-6 2.692-6 6s2.692 6 6 6 6-2.692 6-6-2.692-6-6-6zm0 10c-2.206 0-4-1.794-4-4s1.794-4 4-4 4 1.794 4 4-1.794 4-4 4zM84 6h-6v12h2v-4h4c2.206 0 4-1.794 4-4s-1.794-4-4-4zm0 6h-4V8h4c1.103 0 2 .897 2 2s-.897 2-2 2zM94 6h2v12h-2zM107 6h-4c-1.103 0-2 .897-2 2v8c0 1.103.897 2 2 2h4c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2zm0 10h-4V8h4v8z"/>
              </svg>
            </div>
            <div class="h-6 w-auto">
              <svg class="h-full w-auto text-gray-400" viewBox="0 0 124 24" fill="currentColor">
                <path d="M24 12c0 6.627-5.373 12-12 12S0 18.627 0 12 5.373 0 12 0s12 5.373 12 12zm-4 0c0-4.418-3.582-8-8-8s-8 3.582-8 8 3.582 8 8 8 8-3.582 8-8zM44 6h-6v12h2v-4h4c2.206 0 4-1.794 4-4s-1.794-4-4-4zm0 6h-4V8h4c1.103 0 2 .897 2 2s-.897 2-2 2zM57 18h2V6h-2zM66 6c-3.308 0-6 2.692-6 6s2.692 6 6 6 6-2.692 6-6-2.692-6-6-6zm0 10c-2.206 0-4-1.794-4-4s1.794-4 4-4 4 1.794 4 4-1.794 4-4 4zM84 6h-6v12h2v-4h4c2.206 0 4-1.794 4-4s-1.794-4-4-4zm0 6h-4V8h4c1.103 0 2 .897 2 2s-.897 2-2 2zM94 6h2v12h-2zM107 6h-4c-1.103 0-2 .897-2 2v8c0 1.103.897 2 2 2h4c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2zm0 10h-4V8h4v8z"/>
              </svg>
            </div>
            <div class="h-7 w-auto">
              <svg class="h-full w-auto text-gray-400" viewBox="0 0 124 24" fill="currentColor">
                <path d="M24 12c0 6.627-5.373 12-12 12S0 18.627 0 12 5.373 0 12 0s12 5.373 12 12zm-4 0c0-4.418-3.582-8-8-8s-8 3.582-8 8 3.582 8 8 8 8-3.582 8-8zM44 6h-6v12h2v-4h4c2.206 0 4-1.794 4-4s-1.794-4-4-4zm0 6h-4V8h4c1.103 0 2 .897 2 2s-.897 2-2 2zM57 18h2V6h-2zM66 6c-3.308 0-6 2.692-6 6s2.692 6 6 6 6-2.692 6-6-2.692-6-6-6zm0 10c-2.206 0-4-1.794-4-4s1.794-4 4-4 4 1.794 4 4-1.794 4-4 4zM84 6h-6v12h2v-4h4c2.206 0 4-1.794 4-4s-1.794-4-4-4zm0 6h-4V8h4c1.103 0 2 .897 2 2s-.897 2-2 2zM94 6h2v12h-2zM107 6h-4c-1.103 0-2 .897-2 2v8c0 1.103.897 2 2 2h4c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2zm0 10h-4V8h4v8z"/>
              </svg>
            </div>
          </div>
        </div>
      </UContainer>
    </section>

    <!-- Features Section -->
    <section id="features" class="py-24 bg-white">
      <UContainer>
        <div class="text-center space-y-4 mb-16">
          <div class="inline-flex items-center px-3 py-1 rounded-full bg-blue-100 text-blue-800 text-sm font-medium mb-2">
            <UIcon name="i-heroicons-star" class="w-4 h-4 mr-2" />
            Key Features
          </div>
          <h2 class="text-3xl lg:text-4xl font-bold text-gray-900">
            Why Choose AI Learning Hub?
          </h2>
          <p class="text-xl text-gray-600 max-w-3xl mx-auto">
            Our AI-powered platform adapts to your learning style, schedule, and goals 
            to create the perfect learning experience.
          </p>
        </div>
        
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div class="group relative bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-lg hover:border-primary-100 transition-all duration-300">
            <div class="absolute top-0 right-0 w-24 h-24 bg-primary-100 rounded-bl-2xl rounded-tr-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            <div class="relative z-10">
              <div class="w-14 h-14 bg-primary-100 rounded-xl flex items-center justify-center mb-6 group-hover:bg-primary-200 transition-colors duration-300">
                <UIcon name="i-heroicons-sparkles" class="w-7 h-7 text-primary-600" />
              </div>
              <h3 class="text-xl font-semibold text-gray-900 mb-3">AI-Generated Courses</h3>
              <p class="text-gray-600">Request any topic and get a complete course with lessons, quizzes, and projects tailored to your level.</p>
            </div>
          </div>
          
          <div class="group relative bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-lg hover:border-blue-100 transition-all duration-300">
            <div class="absolute top-0 right-0 w-24 h-24 bg-blue-100 rounded-bl-2xl rounded-tr-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            <div class="relative z-10">
              <div class="w-14 h-14 bg-blue-100 rounded-xl flex items-center justify-center mb-6 group-hover:bg-blue-200 transition-colors duration-300">
                <UIcon name="i-heroicons-calendar" class="w-7 h-7 text-blue-600" />
              </div>
              <h3 class="text-xl font-semibold text-gray-900 mb-3">Smart Scheduling</h3>
              <p class="text-gray-600">AI creates a personalized study schedule based on your availability and learning goals.</p>
            </div>
          </div>
          
          <div class="group relative bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-lg hover:border-green-100 transition-all duration-300">
            <div class="absolute top-0 right-0 w-24 h-24 bg-green-100 rounded-bl-2xl rounded-tr-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            <div class="relative z-10">
              <div class="w-14 h-14 bg-green-100 rounded-xl flex items-center justify-center mb-6 group-hover:bg-green-200 transition-colors duration-300">
                <UIcon name="i-heroicons-chart-bar" class="w-7 h-7 text-green-600" />
              </div>
              <h3 class="text-xl font-semibold text-gray-900 mb-3">Progress Tracking</h3>
              <p class="text-gray-600">Monitor your learning journey with detailed analytics and personalized recommendations.</p>
            </div>
          </div>
          
          <div class="group relative bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-lg hover:border-purple-100 transition-all duration-300">
            <div class="absolute top-0 right-0 w-24 h-24 bg-purple-100 rounded-bl-2xl rounded-tr-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            <div class="relative z-10">
              <div class="w-14 h-14 bg-purple-100 rounded-xl flex items-center justify-center mb-6 group-hover:bg-purple-200 transition-colors duration-300">
                <UIcon name="i-heroicons-puzzle-piece" class="w-7 h-7 text-purple-600" />
              </div>
              <h3 class="text-xl font-semibold text-gray-900 mb-3">Interactive Quizzes</h3>
              <p class="text-gray-600">Test your knowledge with AI-generated quizzes that adapt to your understanding level.</p>
            </div>
          </div>
          
          <div class="group relative bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-lg hover:border-orange-100 transition-all duration-300">
            <div class="absolute top-0 right-0 w-24 h-24 bg-orange-100 rounded-bl-2xl rounded-tr-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            <div class="relative z-10">
              <div class="w-14 h-14 bg-orange-100 rounded-xl flex items-center justify-center mb-6 group-hover:bg-orange-200 transition-colors duration-300">
                <UIcon name="i-heroicons-device-phone-mobile" class="w-7 h-7 text-orange-600" />
              </div>
              <h3 class="text-xl font-semibold text-gray-900 mb-3">Mobile Learning</h3>
              <p class="text-gray-600">Learn anywhere, anytime with our responsive platform that works on all devices.</p>
            </div>
          </div>
          
          <div class="group relative bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-lg hover:border-pink-100 transition-all duration-300">
            <div class="absolute top-0 right-0 w-24 h-24 bg-pink-100 rounded-bl-2xl rounded-tr-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            <div class="relative z-10">
              <div class="w-14 h-14 bg-pink-100 rounded-xl flex items-center justify-center mb-6 group-hover:bg-pink-200 transition-colors duration-300">
                <UIcon name="i-heroicons-users" class="w-7 h-7 text-pink-600" />
              </div>
              <h3 class="text-xl font-semibold text-gray-900 mb-3">Community Support</h3>
              <p class="text-gray-600">Connect with other learners and get help from our supportive community.</p>
            </div>
          </div>
        </div>
      </UContainer>
    </section>

    <!-- How It Works Section -->
    <section id="how-it-works" class="py-24 bg-gray-50 relative overflow-hidden">
      <div class="absolute inset-0 bg-grid-pattern opacity-5"></div>
      <div class="absolute -top-24 -left-24 w-96 h-96 bg-yellow-300 rounded-full filter blur-3xl opacity-10"></div>
      <div class="absolute -bottom-24 -right-24 w-96 h-96 bg-primary-300 rounded-full filter blur-3xl opacity-10"></div>
      
      <UContainer class="relative z-10">
        <div class="text-center space-y-4 mb-16">
          <div class="inline-flex items-center px-3 py-1 rounded-full bg-green-100 text-green-800 text-sm font-medium mb-2">
            <UIcon name="i-heroicons-arrow-path" class="w-4 h-4 mr-2" />
            Simple Process
          </div>
          <h2 class="text-3xl lg:text-4xl font-bold text-gray-900">
            How It Works
          </h2>
          <p class="text-xl text-gray-600">
            Get started with AI-powered learning in just 3 simple steps
          </p>
        </div>
        
        <div class="relative">
          <!-- Connection line -->
          <div class="absolute top-24 left-1/2 transform -translate-x-1/2 w-2/3 h-0.5 bg-gray-200 hidden md:block"></div>
          
          <div class="grid grid-cols-1 md:grid-cols-3 gap-12">
            <div class="relative flex flex-col items-center text-center">
              <div class="w-20 h-20 bg-primary-600 rounded-full flex items-center justify-center mb-6 z-10">
                <span class="text-2xl font-bold text-white">1</span>
              </div>
              <h3 class="text-xl font-semibold text-gray-900 mb-3">Tell Us What You Want to Learn</h3>
              <p class="text-gray-600">Simply describe the topic, your current level, and your learning goals. Our AI will understand your needs.</p>
              
              <div class="mt-6 w-full max-w-xs mx-auto bg-white rounded-xl shadow-md p-4 border border-gray-100">
                <div class="flex items-center space-x-3 mb-3">
                  <div class="w-8 h-8 bg-primary-100 rounded-lg flex items-center justify-center">
                    <UIcon name="i-heroicons-chat-bubble-left-right" class="w-4 h-4 text-primary-600" />
                  </div>
                  <div class="text-sm font-medium text-gray-900">Course Request</div>
                </div>
                <div class="space-y-2 text-xs text-left">
                  <div class="flex items-center space-x-2">
                    <span class="text-gray-500">Topic:</span>
                    <span class="font-medium text-gray-900">JavaScript Fundamentals</span>
                  </div>
                  <div class="flex items-center space-x-2">
                    <span class="text-gray-500">Level:</span>
                    <span class="font-medium text-gray-900">Beginner</span>
                  </div>
                  <div class="flex items-center space-x-2">
                    <span class="text-gray-500">Goal:</span>
                    <span class="font-medium text-gray-900">Web Development</span>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="relative flex flex-col items-center text-center">
              <div class="w-20 h-20 bg-primary-600 rounded-full flex items-center justify-center mb-6 z-10">
                <span class="text-2xl font-bold text-white">2</span>
              </div>
              <h3 class="text-xl font-semibold text-gray-900 mb-3">Get Your Personalized Course</h3>
              <p class="text-gray-600">AI generates a complete course with lessons, quizzes, and a schedule that fits your availability.</p>
              
              <div class="mt-6 w-full max-w-xs mx-auto bg-white rounded-xl shadow-md p-4 border border-gray-100">
                <div class="flex items-center space-x-3 mb-3">
                  <div class="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center">
                    <UIcon name="i-heroicons-cog-6-tooth" class="w-4 h-4 text-blue-600" />
                  </div>
                  <div class="text-sm font-medium text-gray-900">AI Course Generation</div>
                </div>
                <div class="space-y-2">
                  <div class="w-full bg-gray-100 h-2 rounded-full overflow-hidden">
                    <div class="bg-blue-600 h-full w-3/4 animate-pulse"></div>
                  </div>
                  <div class="text-xs text-gray-500 text-center">Generating course content...</div>
                </div>
              </div>
            </div>
            
            <div class="relative flex flex-col items-center text-center">
              <div class="w-20 h-20 bg-primary-600 rounded-full flex items-center justify-center mb-6 z-10">
                <span class="text-2xl font-bold text-white">3</span>
              </div>
              <h3 class="text-xl font-semibold text-gray-900 mb-3">Learn and Track Progress</h3>
              <p class="text-gray-600">Follow your personalized learning path, take quizzes, and watch your skills grow with detailed analytics.</p>
              
              <div class="mt-6 w-full max-w-xs mx-auto bg-white rounded-xl shadow-md p-4 border border-gray-100">
                <div class="flex items-center space-x-3 mb-3">
                  <div class="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center">
                    <UIcon name="i-heroicons-chart-bar-square" class="w-4 h-4 text-green-600" />
                  </div>
                  <div class="text-sm font-medium text-gray-900">Learning Analytics</div>
                </div>
                <div class="grid grid-cols-2 gap-2 text-xs">
                  <div class="bg-gray-50 p-2 rounded">
                    <div class="font-medium text-gray-900">85%</div>
                    <div class="text-gray-500">Quiz Score</div>
                  </div>
                  <div class="bg-gray-50 p-2 rounded">
                    <div class="font-medium text-gray-900">12h</div>
                    <div class="text-gray-500">Study Time</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <!-- CTA Button -->
        <div class="mt-16 text-center">
          <UButton to="/auth/register" size="lg" class="px-8">
            Start Your Learning Journey
            <UIcon name="i-heroicons-arrow-right" class="w-5 h-5 ml-2" />
          </UButton>
        </div>
      </UContainer>
    </section>

    <!-- Testimonials Section -->
    <section class="py-24 bg-white">
      <UContainer>
        <div class="text-center space-y-4 mb-16">
          <div class="inline-flex items-center px-3 py-1 rounded-full bg-yellow-100 text-yellow-800 text-sm font-medium mb-2">
            <UIcon name="i-heroicons-chat-bubble-bottom-center-text" class="w-4 h-4 mr-2" />
            Success Stories
          </div>
          <h2 class="text-3xl lg:text-4xl font-bold text-gray-900">
            What Our Learners Say
          </h2>
          <p class="text-xl text-gray-600 max-w-3xl mx-auto">
            Join thousands of satisfied learners who have transformed their skills with our AI-powered platform
          </p>
        </div>
        
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">
          <!-- Featured testimonial -->
          <div class="lg:col-span-6 bg-gradient-to-br from-primary-50 to-blue-50 rounded-2xl p-8 relative">
            <div class="absolute top-6 right-6">
              <svg width="42" height="36" viewBox="0 0 42 36" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M16.0022 0C7.1633 0 0 7.1633 0 16.0022C0 24.8411 7.1633 32.0044 16.0022 32.0044C24.8411 32.0044 32.0044 24.8411 32.0044 16.0022C32.0044 7.1633 24.8411 0 16.0022 0ZM16.0022 26.0036C10.4814 26.0036 6.00089 21.523 6.00089 16.0022C6.00089 10.4814 10.4814 6.00089 16.0022 6.00089C21.523 6.00089 26.0036 10.4814 26.0036 16.0022C26.0036 21.523 21.523 26.0036 16.0022 26.0036Z" fill="#E0E7FF" fill-opacity="0.8"/>
                <path d="M36.0049 0C27.166 0 20.0027 7.1633 20.0027 16.0022C20.0027 24.8411 27.166 32.0044 36.0049 32.0044C44.8438 32.0044 52.0071 24.8411 52.0071 16.0022C52.0071 7.1633 44.8438 0 36.0049 0ZM36.0049 26.0036C30.4841 26.0036 26.0036 21.523 26.0036 16.0022C26.0036 10.4814 30.4841 6.00089 36.0049 6.00089C41.5257 6.00089 46.0062 10.4814 46.0062 16.0022C46.0062 21.523 41.5257 26.0036 36.0049 26.0036Z" fill="#E0E7FF" fill-opacity="0.8"/>
              </svg>
            </div>
            
            <div class="flex flex-col h-full justify-between">
              <div>
                <div class="flex items-center space-x-1 text-yellow-400 mb-6">
                  <UIcon v-for="i in 5" :key="i" name="i-heroicons-star-solid" class="w-5 h-5" />
                </div>
                
                <blockquote class="text-xl text-gray-700 italic mb-6">
                  "The AI-generated courses are incredibly detailed and perfectly match my learning style. I've learned more in 2 months than I did in a year of traditional courses. The personalized schedule makes it easy to stay consistent."
                </blockquote>
              </div>
              
              <div class="flex items-center space-x-4">
                <UAvatar src="/placeholder.svg?height=60&width=60" alt="Sarah Chen" size="lg" />
                <div>
                  <p class="font-semibold text-gray-900">Sarah Chen</p>
                  <p class="text-gray-600">Software Developer</p>
                </div>
              </div>
            </div>
          </div>
          
          <!-- Secondary testimonials -->
          <div class="lg:col-span-6 grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="bg-white border border-gray-100 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow">
              <div class="flex items-center space-x-1 text-yellow-400 mb-4">
                <UIcon v-for="i in 5" :key="i" name="i-heroicons-star-solid" class="w-4 h-4" />
              </div>
              
              <blockquote class="text-gray-700 mb-4">
                "The smart scheduling feature is a game-changer. It fits perfectly with my busy schedule and keeps me motivated to continue learning."
              </blockquote>
              
              <div class="flex items-center space-x-3">
                <UAvatar src="/placeholder.svg?height=40&width=40" alt="Marcus Johnson" size="sm" />
                <div>
                  <p class="font-semibold text-gray-900">Marcus Johnson</p>
                  <p class="text-sm text-gray-600">Marketing Manager</p>
                </div>
              </div>
            </div>
            
            <div class="bg-white border border-gray-100 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow">
              <div class="flex items-center space-x-1 text-yellow-400 mb-4">
                <UIcon v-for="i in 5" :key="i" name="i-heroicons-star-solid" class="w-4 h-4" />
              </div>
              
              <blockquote class="text-gray-700 mb-4">
                "I love how the platform adapts to my progress. The quizzes get more challenging as I improve, keeping me engaged throughout my learning journey."
              </blockquote>
              
              <div class="flex items-center space-x-3">
                <UAvatar src="/placeholder.svg?height=40&width=40" alt="Emily Rodriguez" size="sm" />
                <div>
                  <p class="font-semibold text-gray-900">Emily Rodriguez</p>
                  <p class="text-sm text-gray-600">Data Analyst</p>
                </div>
              </div>
            </div>
            
            <div class="bg-white border border-gray-100 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow">
              <div class="flex items-center space-x-1 text-yellow-400 mb-4">
                <UIcon v-for="i in 5" :key="i" name="i-heroicons-star-solid" class="w-4 h-4" />
              </div>
              
              <blockquote class="text-gray-700 mb-4">
                "As a teacher, I'm impressed by the quality of content. The AI creates comprehensive courses that I can recommend to my students for additional practice."
              </blockquote>
              
              <div class="flex items-center space-x-3">
                <UAvatar src="/placeholder.svg?height=40&width=40" alt="David Kim" size="sm" />
                <div>
                  <p class="font-semibold text-gray-900">David Kim</p>
                  <p class="text-sm text-gray-600">High School Teacher</p>
                </div>
              </div>
            </div>
            
            <div class="bg-white border border-gray-100 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow">
              <div class="flex items-center space-x-1 text-yellow-400 mb-4">
                <UIcon v-for="i in 5" :key="i" name="i-heroicons-star-solid" class="w-4 h-4" />
              </div>
              
              <blockquote class="text-gray-700 mb-4">
                "The community support is fantastic. Whenever I get stuck, there's always someone ready to help. It's like having a personal tutor available 24/7."
              </blockquote>
              
              <div class="flex items-center space-x-3">
                <UAvatar src="/placeholder.svg?height=40&width=40" alt="Olivia Martinez" size="sm" />
                <div>
                  <p class="font-semibold text-gray-900">Olivia Martinez</p>
                  <p class="text-sm text-gray-600">UX Designer</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </UContainer>
    </section>

    <!-- Stats Section -->
    <section class="py-16 bg-gray-50">
      <UContainer>
        <div class="grid grid-cols-2 md:grid-cols-4 gap-8">
          <div class="text-center">
            <div class="text-4xl font-bold text-primary-600 mb-2">10,000+</div>
            <div class="text-gray-600">Active Learners</div>
          </div>
          <div class="text-center">
            <div class="text-4xl font-bold text-primary-600 mb-2">500+</div>
            <div class="text-gray-600">Course Topics</div>
          </div>
          <div class="text-center">
            <div class="text-4xl font-bold text-primary-600 mb-2">98%</div>
            <div class="text-gray-600">Satisfaction Rate</div>
          </div>
          <div class="text-center">
            <div class="text-4xl font-bold text-primary-600 mb-2">24/7</div>
            <div class="text-gray-600">Support</div>
          </div>
        </div>
      </UContainer>
    </section>

    <!-- CTA Section -->
    <section class="py-20 bg-gradient-to-r from-primary-600 to-blue-600 relative overflow-hidden">
      <div class="absolute inset-0 bg-pattern opacity-10"></div>
      <div class="absolute -top-24 -left-24 w-96 h-96 bg-white rounded-full filter blur-3xl opacity-10"></div>
      <div class="absolute -bottom-24 -right-24 w-96 h-96 bg-white rounded-full filter blur-3xl opacity-10"></div>
      
      <UContainer class="relative z-10">
        <div class="text-center space-y-8 max-w-3xl mx-auto">
          <div class="space-y-4">
            <h2 class="text-3xl lg:text-4xl font-bold text-white">
              Ready to Transform Your Learning?
            </h2>
            <p class="text-xl text-primary-100">
              Join thousands of learners who are already using AI to accelerate their education.
              Start your free trial today.
            </p>
          </div>
          
          <div class="flex flex-col sm:flex-row gap-4 justify-center">
            <UButton to="/auth/register" size="xl" color="white" class="justify-center">
              Start Free Trial
              <UIcon name="i-heroicons-arrow-right" class="w-5 h-5 ml-2" />
            </UButton>
            <UButton to="/pricing" variant="outline" size="xl" color="white" class="justify-center">
              View Pricing
            </UButton>
          </div>
          
          <div class="flex flex-wrap justify-center gap-6 text-sm text-white">
            <div class="flex items-center space-x-2">
              <UIcon name="i-heroicons-check-circle" class="w-5 h-5" />
              <span>No credit card required</span>
            </div>
            <div class="flex items-center space-x-2">
              <UIcon name="i-heroicons-check-circle" class="w-5 h-5" />
              <span>14-day free trial</span>
            </div>
            <div class="flex items-center space-x-2">
              <UIcon name="i-heroicons-check-circle" class="w-5 h-5" />
              <span>Cancel anytime</span>
            </div>
          </div>
        </div>
      </UContainer>
    </section>
  </div>
</template>

<script setup>
// Component is self-contained
</script>

<style scoped>
.bg-grid-pattern {
  background-image: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%239C92AC' fill-opacity='0.1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
}

.bg-pattern {
  background-image: url("data:image/svg+xml,%3Csvg width='100' height='100' viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M11 18c3.866 0 7-3.134 7-7s-3.134-7-7-7-7 3.134-7 7 3.134 7 7 7zm48 25c3.866 0 7-3.134 7-7s-3.134-7-7-7-7 3.134-7 7 3.134 7 7 7zm-43-7c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zm63 31c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zM34 90c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zm56-76c1.657 0 3-1.343 3-3s-1.343-3-3-3-3 1.343-3 3 1.343 3 3 3zM12 86c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm28-65c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm23-11c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zm-6 60c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm29 22c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zM32 63c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zm57-13c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5zm-9-21c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zM60 91c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zM35 41c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zM12 60c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2z' fill='%23ffffff' fill-opacity='0.1' fill-rule='evenodd'/%3E%3C/svg%3E");
}
</style>
