name: Build and Deploy

on:
  push:
    branches: [Staging, Prod]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FRONTEND: ${{ github.repository }}/frontend
  IMAGE_NAME_BACKEND: ${{ github.repository }}/backend

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      frontend-image: ${{ steps.meta-frontend.outputs.tags }}
      user-image: ${{ steps.meta-user.outputs.tags }}
      course-image: ${{ steps.meta-course.outputs.tags }}
      schedule-image: ${{ steps.meta-schedule.outputs.tags }}
      api-gateway-image: ${{ steps.meta-apigateway.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./nuxt-app
          file: ./nuxt-app/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      ## Build User Microservice
      - name: Extract metadata for user microservice
        id: meta-user
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/user
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-

      - name: Build and push user microservice
        uses: docker/build-push-action@v5
        with:
          context: ./back/nest-back
          file: ./back/nest-back/Dockerfile.user
          push: true
          tags: ${{ steps.meta-user.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      ## Build Course Microservice
      - name: Extract metadata for course microservice
        id: meta-course
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/course
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-

      - name: Build and push course microservice
        uses: docker/build-push-action@v5
        with:
          context: ./back/nest-back
          file: ./back/nest-back/Dockerfile.course
          push: true
          tags: ${{ steps.meta-course.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      ## Build Schedule Microservice
      - name: Extract metadata for schedule microservice
        id: meta-schedule
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/schedule
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-

      - name: Build and push schedule microservice
        uses: docker/build-push-action@v5
        with:
          context: ./back/nest-back
          file: ./back/nest-back/Dockerfile.schedule
          push: true
          tags: ${{ steps.meta-schedule.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      ## Build API Gateway Microservice
      - name: Extract metadata for api-gateway microservice
        id: meta-apigateway
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/api-gateway
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-

      - name: Build and push api-gateway microservice
        uses: docker/build-push-action@v5
        with:
          context: ./back/nest-back
          file: ./back/nest-back/Dockerfile.api
          push: true
          tags: ${{ steps.meta-apigateway.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Staging' || github.ref == 'refs/heads/Prod'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GITHUB_SHA,GITHUB_REF_NAME
          script: |
            cd /home/ubuntu/LearningAI
            
            # Login au registry GitHub
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Pull du nouveau code
            git pull origin $GITHUB_REF_NAME
            
            # Variables d'environnement pour les images
            export FRONTEND_IMAGE=$(echo "${{ needs.build.outputs.frontend-image }}" | head -n1)
            export USER_IMAGE=$(echo "${{ needs.build.outputs.user-image }}" | head -n1)
            export COURSE_IMAGE=$(echo "${{ needs.build.outputs.course-image }}" | head -n1)
            export SCHEDULE_IMAGE=$(echo "${{ needs.build.outputs.schedule-image }}" | head -n1)
            export API_GATEWAY_IMAGE=$(echo "${{ needs.build.outputs.api-gateway-image }}" | head -n1)

            
            echo "Frontend image: $FRONTEND_IMAGE"
            echo "User image: $USER_IMAGE"
            echo "Course image: $COURSE_IMAGE"
            echo "Schedule image: $SCHEDULE_IMAGE"
            echo "API Gateway image: $API_GATEWAY_IMAGE"

            
            # Déploiement
            docker compose down
            docker compose pull
            docker compose up -d
            
            # Nettoyage
            docker image prune -f
            
            # Status
            docker compose ps