name: Deploy to EC2
on:
  push:
    branches: [Staging, Prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 30m
          script: |
            cd /home/ubuntu/LearningAI
          
            git pull origin Staging
            
            docker system prune -f
            
            docker compose down
            
            docker compose build --parallel
            docker compose up -d
            
            sleep 10
            docker compose ps